--- 
parameter: 
  repository: 
    - 
      name: Master_Repository
      branch: master
      url: Master_Repository_URL 
    - 
      name: Dev_Repository
      branch: dev
      url: Dev_Repository_URL 
    - 
      name: Stage_Repository
      branch: Stage
      url: Stage_Repository_URL 
