--- 
parameter: 
  parameter1_repo1: 
    - 
      DefaultValues: ssdtestpipeline
      Type: String
      name: parameter1_repo1_gitlab_target_name1
    - 
      DefaultValues: parameter_name_2
      Type: String
      name: parameter1_repo1_gitlab_target_name2
